import { classifyBusinessContext, getPhaseAdaptationRules, generateContextProfileMarkdown } from "../data/businessContextRouter.js";
import { ALL_PHASES_QUESTIONS, getAdaptedPhaseQuestions } from "../data/allPhasesTemplates.js";
import { getAdaptivePhase2Questions } from "../data/phase2Templates.js";
import { WIKI_PLAYBOOKS } from "../data/wikiKnowledge.js";
import { generateDeliverable } from './deliverableGenerator.js';
import { composeChainedQuestions, DYNAMIC_QUESTION_FORMULA } from './dynamicQuestionEngine.js';
import { detectUnknownIntent, parseSemanticInput, parseFreeformSemanticSlots, UNKNOWN_CATEGORIES } from './semanticParser.js';
import { validatePhaseGate } from "./phaseGateValidator.js";
import { UnknownsManager, UNKNOWN_SEVERITY, UNKNOWN_STATUS } from "./unknownsManager.js";
import { ContradictionEngine, CONTRADICTION_SEVERITY, CONTRADICTION_STATUS } from "./contradictionEngine.js";

/**
 * 4-State Lifecycle for AI-generated dynamic questions (Requirement R13, Feature 10)
 */
export const DYNAMIC_QUESTION_STATE = {
  PENDING: "PENDING",     // Generated by AI Brain, ready to be presented
  ACTIVE: "ACTIVE",       // Currently displayed to user as current question
  CONSUMED: "CONSUMED",   // User has answered; state recorded
  ARCHIVED: "ARCHIVED"    // Retired to history, cannot cause repeat loops
};

export class OrchestratorEngine {
  constructor() {
    this.currentPhase = 1;
    this.currentStepIndex = 0;
    this.isNavigatingBack = false;

    this.completedPhases = {
      1: false, 2: false, 3: false, 4: false, 5: false, 6: false, 7: false, 8: false
    };

    this.phaseStatus = {};

    // Store responses across all 8 phases
    this.phaseData = {
      1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}
    };

    this.facts = [];
    this.decisions = [];
    this.assumptions = [];
    this.unknowns = [];
    this.contradictions = [];
    this.businessContext = null;

    // 4-state dynamic question lifecycle state machine
    this.dynamicQuestion = null; // { id, title, text, whyItMatters, options, state, createdAt, source }
    this.dynamicQuestionState = null;
    this.dynamicQuestionsHistory = [];
    this.dynamicQuestionOverride = null; // legacy backwards-compatible alias
  }

  setBusinessContext(context) {
    this.businessContext = context;
  }

  setContext(context) {
    this.businessContext = context;
  }

  addStrategicDecision(statement) {
    if (!statement || typeof statement !== "string") return;
    const clean = statement.trim();
    if (!clean) return;
    this.decisions.push({
      id: `DECISION-AI-${this.decisions.length + 1}`,
      statement: clean,
      source: "KNOWLEDGE_BRAIN_AI",
      timestamp: new Date().toISOString()
    });
  }

  /**
   * Enqueues a dynamic AI question using the 4-state lifecycle state machine.
   * Protects against infinite loops, stale overrides, and repeat questions.
   */
  setDynamicNextQuestion(question) {
    if (!question || (!question.text && !question.title)) return null;
    const qId = question.id || `dynamic_q_${Date.now()}`;

    // Loop protection: check if identical question already archived
    const isDuplicate = this.dynamicQuestionsHistory.some(
      h => h.id === qId || (h.text && question.text && h.text.trim() === question.text.trim())
    );
    if (isDuplicate) {
      console.warn(`[DynamicQuestionEngine] Duplicate dynamic question '${qId}' rejected to prevent loops.`);
      return null;
    }

    const dynRecord = {
      ...question,
      id: qId,
      state: DYNAMIC_QUESTION_STATE.PENDING,
      createdAt: new Date().toISOString(),
      source: question.source || 'KNOWLEDGE_BRAIN_AI'
    };

    this.dynamicQuestion = dynRecord;
    this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.PENDING;

    // Legacy backwards-compatible mirror
    this.dynamicQuestionOverride = {
      question: dynRecord,
      consumed: false,
      createdAt: dynRecord.createdAt,
      source: dynRecord.source
    };

    return dynRecord;
  }

  getDynamicQuestionState() {
    return this.dynamicQuestionState;
  }

  getDynamicQuestionsHistory() {
    return [...this.dynamicQuestionsHistory];
  }

  clearDynamicQuestion() {
    if (this.dynamicQuestion) {
      this.dynamicQuestionsHistory.push({
        ...this.dynamicQuestion,
        state: DYNAMIC_QUESTION_STATE.ARCHIVED,
        cancelledAt: new Date().toISOString()
      });
    }
    this.dynamicQuestion = null;
    this.dynamicQuestionState = null;
    this.dynamicQuestionOverride = null;
  }

  getCurrentPhaseQuestions() {
    return composeChainedQuestions(
      this.currentPhase,
      this.businessContext,
      this.phaseData,
      this.unknowns,
      this.phaseData[1]?.diagnosticVision || ""
    );
  }

  getCurrentQuestion() {
    // Dynamic question lifecycle check (PENDING -> ACTIVE)
    if (this.dynamicQuestion) {
      if (this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.PENDING || this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.ACTIVE) {
        this.dynamicQuestion.state = DYNAMIC_QUESTION_STATE.ACTIVE;
        this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.ACTIVE;
        return this.dynamicQuestion;
      }
    } else if (this.dynamicQuestionOverride && !this.dynamicQuestionOverride.consumed) {
      return this.dynamicQuestionOverride.question;
    }
    const questions = this.getCurrentPhaseQuestions();
    if (!questions || questions.length === 0) return null;

    // If user explicitly navigated back, return the question at currentStepIndex
    if (this.isNavigatingBack && this.currentStepIndex >= 0 && this.currentStepIndex < questions.length) {
      return questions[this.currentStepIndex];
    }

    // Check if all questions in the current phase are already answered
    const hasUnanswered = questions.some(q => q && !q.isAnswered);
    if (!hasUnanswered) {
      return null;
    }

    // Dynamically find the first question in the current phase that has not been answered yet!
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      if (q && !q.isAnswered) {
        this.currentStepIndex = i;
        return q;
      }
    }

    return null;
  }

  canStartPhase(phaseNum) {
    if (typeof phaseNum !== "number" && typeof phaseNum !== "string") {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    if (Array.isArray(phaseNum)) {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    if (typeof phaseNum === "string" && phaseNum.trim() === "") {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    const p = Number(phaseNum);
    if (isNaN(p) || !Number.isInteger(p) || p < 1 || p > 8) {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }

    if (p === 1) {
      return { allowed: true };
    }

    // Phase N can ONLY be opened if Phase N-1 has passed its exit gate
    if (!this.completedPhases[p - 1]) {
      return {
        allowed: false,
        reason: `ورود به فاز ${p} مجاز نیست. فاز پیش‌نیاز ${p - 1} هنوز تکمیل و تایید نشده است. سیستم دیجیتال مارکت از پرش فازها جلوگیری می‌کند.`
      };
    }

    // Check all earlier phases 1 to p-2 as well
    for (let prev = 1; prev < p - 1; prev++) {
      if (!this.completedPhases[prev]) {
        return {
          allowed: false,
          reason: `ورود به فاز ${p} مجاز نیست. فاز اولیه ${prev} تایید نشده یا ابطال گردیده است.`
        };
      }
    }

    return { allowed: true };
  }

  getPhaseStatus(phaseNum) {
    if (typeof phaseNum !== "number" && typeof phaseNum !== "string") return "INVALID";
    if (Array.isArray(phaseNum)) return "INVALID";
    if (typeof phaseNum === "string" && phaseNum.trim() === "") return "INVALID";
    const p = Number(phaseNum);
    if (isNaN(p) || !Number.isInteger(p) || p < 1 || p > 8) return "INVALID";

    if (this.phaseStatus[p] === "INVALIDATED") {
      return "INVALIDATED";
    }

    if (this.completedPhases[p] === true) {
      return "COMPLETED";
    }

    if (this.currentPhase === p) {
      return "IN_PROGRESS";
    }

    const canStart = this.canStartPhase(p);
    if (canStart.allowed) {
      return "AVAILABLE";
    }

    return "LOCKED";
  }

  invalidateDependentPhases(fromPhase) {
    const p = Number(fromPhase);
    const invalidated = [];

    if (p >= 1 && p < 8) {
      for (let ph = p + 1; ph <= 8; ph++) {
        if (this.completedPhases[ph]) {
          this.completedPhases[ph] = false;
          invalidated.push(ph);
        }
        this.phaseStatus[ph] = "INVALIDATED";
      }
    }

    const message = invalidated.length > 0
      ? `⚠️ **هشدار ابطال فازهای وابسته:** با توجه به تغییر اطلاعات بنیادین در فاز ${p}، خروجی‌های وابسته در فازهای (${invalidated.join("، ")}) نامعتبر شده و نیازمند بازبینی مجدد هستند.`
      : `هیچ فاز تکمیلی وابسته‌ای نیاز به ابطال نداشت.`;

    return {
      fromPhase: p,
      invalidatedPhases: invalidated,
      message
    };
  }

  getQuestionByIndex(index) {
    const questions = this.getCurrentPhaseQuestions();
    const idx = Math.max(0, Math.min(index, questions.length - 1));
    return questions[idx] || null;
  }

  previousQuestion() {
    const questions = this.getCurrentPhaseQuestions();
    if (this.currentStepIndex > 0) {
      this.currentStepIndex--;
    }
    this.isNavigatingBack = true;
    return questions[this.currentStepIndex] || null;
  }

  goToQuestion(index) {
    const questions = this.getCurrentPhaseQuestions();
    const idx = Math.max(0, Math.min(index, questions.length - 1));
    this.currentStepIndex = idx;
    this.isNavigatingBack = true;
    return questions[idx] || null;
  }

  // Controlled transition to phase (1 to 8) enforcing anti-skip protocol
  startPhase(phaseNum) {
    const check = this.canStartPhase(phaseNum);
    if (!check.allowed) {
      const err = new Error(check.reason);
      err.isGateBlocked = true;
      err.phase = phaseNum;
      throw err;
    }

    this.currentPhase = phaseNum;
    this.currentStepIndex = 0;
    this.isNavigatingBack = false;
    if (this.phaseStatus[phaseNum] === "INVALIDATED") {
      delete this.phaseStatus[phaseNum];
    }

    const offer = this.phaseData[1]?.coreOffer || this.phaseData[1]?.description || "خدمات و تخصص محوری";
    const seg = this.phaseData[3]?.targetSegment || "مشتریان ارزش‌محور";
    const char = this.phaseData[4]?.archetype || "رفیق کاربلد و راهنما";
    const voice = this.phaseData[5]?.voiceStyle || "صمیمی و حرفه‌ای";
    const name = this.phaseData[6]?.naming || "برند تخصصی";

    let handoffMsg = "";

    if (phaseNum === 2) {
      handoffMsg = `🔍 **ورود به فاز ۲: هوش بازار و پژوهش مشتری (Market Intelligence)**\n\n` +
        `اطلاعات فاز ۱ به همراه بافتار شناسایی‌شده صنف شما ثبت شد:\n` +
        `- 📌 **صنف و پیشنهاد اصلی:** ${offer}\n` +
        `- 🎯 **آرکی‌تایپ بافتار:** ${this.businessContext?.archetypeTitle || "کسب‌وکار تخصصی"}\n\n` +
        `اکنون تحلیل رقبا، دغدغه و درد مشتریان و فرصت‌های طلایی تمایز را بررسی می‌کنیم:`;
    } else if (phaseNum === 3) {
      handoffMsg = `🎯 **ورود به فاز ۳: استراتژی و جهت‌گیری برند (Brand Strategy)**\n\n` +
        `شواهد هوش بازار فاز ۲ تحویل شد:\n` +
        `- 💡 **درد اصلی بازار:** ${this.phaseData[2]?.customerPain || "کیفیت پایین و عدم همراهی"}\n` +
        `- 🌟 **فرصت طلایی تمایز:** ${this.phaseData[2]?.goldenOpportunity || "سادگی و ضمانت واقعی"}\n\n` +
        `حالا این شواهد را به انتخاب‌های استراتژیک، جایگاه‌یابی منحصربه‌فرد و وعده برند تبدیل می‌کنیم:`;
    } else if (phaseNum === 4) {
      handoffMsg = `✨ **ورود به فاز ۴: هویت و شخصیت برند (Brand Character)**\n\n` +
        `بنیاد استراتژی فاز ۳ تحویل شد:\n` +
        `- 🎯 **بخش هدف:** ${seg}\n` +
        `- 🛡️ **جایگاه تمایز:** ${this.phaseData[3]?.positioning || "ارائه باکیفیت و بدون دردسر"}\n\n` +
        `حالا استراتژی را به یک کاراکتر انسانی ملموس با کهن‌الگو و صفات رفتاری متمایز تبدیل می‌کنیم:`;
    } else if (phaseNum === 5) {
      handoffMsg = `🗣️ **ورود به فاز ۵: سیستم هویت کلامی و پیام‌رسانی (Verbal Identity)**\n\n` +
        `کاراکتر فاز ۴ تحویل شد:\n` +
        `- 🎭 **کهن‌الگو:** ${char}\n` +
        `- 💎 **صفات رفتاری:** ${this.phaseData[4]?.traits || "صادق، دقیق و متعهد"}\n\n` +
        `اکنون صدای برند، لحن، قلاب معرفی آسانسوری ۳۰ ثانیه‌ای و واژگان ممنوعه را طراحی می‌کنیم:`;
    } else if (phaseNum === 6) {
      handoffMsg = `🔥 **ورود به فاز ۶: نام‌گذاری، شعار و جهت‌گیری خلاقانه (Naming & Creative Direction)**\n\n` +
        `هویت کلامی فاز ۵ تحویل شد:\n` +
        `- 📢 **سبک صدا:** ${voice}\n` +
        `- 🎯 **قلاب معرفی:** ${this.phaseData[5]?.elevatorHook || "حل مستقیم درد مخاطب"}\n\n` +
        `حالا قلمرو نام‌گذاری، سبک شعار محوری و بریف دیزاین را مشخص می‌کنیم:`;
    } else if (phaseNum === 7) {
      handoffMsg = `🎨 **ورود به فاز ۷: طراحی سیستم هویت بصری (Visual Identity Design System)**\n\n` +
        `نام و شعار فاز ۶ تحویل شد:\n` +
        `- 🏷️ **نام برند:** ${name}\n` +
        `- ⚡ **شعار:** ${this.phaseData[6]?.tagline || "تعهد پایدار به کیفیت و رضایت"}\n\n` +
        `در این فاز، پالت رنگی روان‌شناختی، تایپوگرافی فارسی و فرم نشان بصری را انتخاب می‌کنیم:`;
    } else if (phaseNum === 8) {
      handoffMsg = `🚀 **ورود به فاز ۸: برنامه فعال‌سازی اجرایی و مدیریت اعتبار (Executive Activation & Reputation)**\n\n` +
        `سیستم کامل ۷ فاز قبلی با موفقیت تصویب شد:\n` +
        `- 🏷️ **نام و هویت برند:** ${name}\n` +
        `- 🎯 **جایگاه و بخش هدف:** ${seg}\n` +
        `- 📢 **سبک پیام و صدا:** ${voice}\n\n` +
        `اکنون برند طراحی‌شده را وارد میدان عملیات می‌کنیم: سئوی محلی/شخصی، رسانه‌ها، قیف تجاری و پروتکل حل بحران:`;
    }

    const adaptationRule = getPhaseAdaptationRules(phaseNum, this.businessContext);
    if (adaptationRule && adaptationRule.instruction) {
      handoffMsg += `\n\n🎯 **انطباق تخصصی بافتار صنف (${this.businessContext?.archetypeTitle || ""}):**\n${adaptationRule.instruction}`;
    }

    const firstQ = this.getCurrentQuestion();
    return {
      welcomeMessage: handoffMsg,
      firstQuestion: firstQ
    };
  }

  processUserResponse(userText, optionValue = null) {
    let currentQ = null;
    let isDynamicResponse = false;

    // 1. Dynamic question lifecycle check (ACTIVE -> CONSUMED -> ARCHIVED)
    if (this.dynamicQuestion && (this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.ACTIVE || this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.PENDING)) {
      currentQ = this.dynamicQuestion;
      this.dynamicQuestion.state = DYNAMIC_QUESTION_STATE.CONSUMED;
      this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.CONSUMED;

      this.dynamicQuestionsHistory.push({
        ...this.dynamicQuestion,
        state: DYNAMIC_QUESTION_STATE.ARCHIVED,
        answeredAt: new Date().toISOString(),
        userAnswer: userText,
        optionValue
      });

      this.dynamicQuestion = null;
      this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.ARCHIVED;
      if (this.dynamicQuestionOverride) {
        this.dynamicQuestionOverride.consumed = true;
      }
      isDynamicResponse = true;
    } else if (this.dynamicQuestionOverride && !this.dynamicQuestionOverride.consumed) {
      currentQ = this.dynamicQuestionOverride.question;
      this.dynamicQuestionOverride.consumed = true;
      isDynamicResponse = true;
    } else if (this.isNavigatingBack) {
      const questions = this.getCurrentPhaseQuestions();
      currentQ = questions[this.currentStepIndex] || this.getCurrentQuestion();
      this.isNavigatingBack = false;
    } else {
      currentQ = this.getCurrentQuestion();
    }
    const qId = currentQ ? currentQ.id : "free_text";
    const phase = this.currentPhase;

    // Multi-pattern unknown detection
    const unknownDetection = detectUnknownIntent(userText);
    const isUnknownIntent =
      unknownDetection.isUnknown ||
      optionValue === "unknown" ||
      userText.includes("نمی‌دانم") ||
      userText.includes("مطمئن نیستم");

    if (isUnknownIntent) {
      const cat = unknownDetection.category || (optionValue === "unknown" ? "EXPLICIT_IGNORANCE" : "UNCERTAINTY");
      const reason = unknownDetection.reason || "ثبت به عنوان مجهول رسمی نیازمند تست یا تحقیق تکمیلی";
      const actionItem = unknownDetection.actionItem || "طراحی و استقرار شیت ثبت روزانه داده‌ها در بازه ۳۰ روزه اولیه برای استخراج عدد واقعی";
      const hypothesis = `[فرضیه نیازمند تست - مجهول رسمی]: داده‌های مربوط به ${currentQ?.title || qId} هنوز به طور قطعی اندازه‌گیری نشده و در فاز ۳۰ روزه اولیه سنجیده خواهد شد.`;

      const unknownEntry = UnknownsManager.createUnknown({
        phase: phase,
        questionId: qId,
        category: cat,
        reason: reason,
        actionItem: actionItem,
        hypothesis: hypothesis,
        owner: "FOUNDER",
        status: UNKNOWN_STATUS.OPEN,
        source: optionValue === "unknown" ? "USER_OPTION" : "USER_TEXT",
        existingCount: this.unknowns.length
      });
      this.unknowns.push(unknownEntry);

      this.assumptions.push({
        id: `A-P${phase}-${this.assumptions.length + 1}`,
        statement: `فرضیه ثبت‌شده برای ${currentQ?.title || qId}: [فرضیه نیازمند تست - مجهول رسمی] (${cat})`,
        actionItem: actionItem
      });

      // Avoid forcing fake numbers into phaseData
      if (this.phaseData[phase]) {
        this.phaseData[phase][qId] = "[فرضیه نیازمند تست - مجهول رسمی]";
        if (qId.includes("unit_economics")) this.phaseData[phase].unitEconomics = "[فرضیه نیازمند تست - مجهول رسمی]";
        if (qId.includes("geography")) this.phaseData[phase].geography = "[فرضیه نیازمند تست - مجهول رسمی]";
        if (qId.includes("primary_goal")) this.phaseData[phase].primaryGoal = "[فرضیه نیازمند تست - مجهول رسمی]";
        if (qId.includes("core_offer")) this.phaseData[phase].coreOffer = "[فرضیه نیازمند تست - مجهول رسمی]";
      }

      this.currentStepIndex++;
      const nextQ = this.getCurrentQuestion();
      if (!nextQ) {
        return this.finalizeCurrentPhase();
      }
      return {
        reply: `این مورد در دسته **«${cat}»** به عنوان یک **مجهول رسمی و فرضیه نیازمند تست** در دوسیه استراتژیک ثبت شد. ندانستن یا نداشتن آمار، بسیار بهتر از تصمیم‌گیری بر مبنای حدس و عدد ساختگی است! ✔️\n\n📌 **اقدام حقیقت‌یابی:** ${actionItem}\n\nبرویم به گام بعدی:`,
        nextQuestion: nextQ,
        isCompleted: false
      };
    }

    // Freeform slot parsing and facts/context enrichment
    const semanticResult = parseSemanticInput(userText, this.businessContext);
    const slots = semanticResult.extractedSlots;

    if (slots) {
      if (slots.customerModel && !this.phaseData[1].customerModel) {
        this.phaseData[1].customerModel = slots.customerModel;
        this.facts.push({
          id: `FACT-FREEFORM-MODEL-${this.facts.length + 1}`,
          statement: `مدل مشتری استخراج‌شده از تحلیل متن آزاد: ${slots.customerModel}`
        });
      }
      if (slots.channels && !this.phaseData[1].channelModel) {
        this.phaseData[1].channelModel = slots.channels;
        this.facts.push({
          id: `FACT-FREEFORM-CHANNEL-${this.facts.length + 1}`,
          statement: `کانال توزیع استخراج‌شده از تحلیل متن آزاد: ${slots.channels}`
        });
      }
      if (slots.scale && !this.phaseData[1].scale) {
        this.phaseData[1].scale = slots.scale;
        this.facts.push({
          id: `FACT-FREEFORM-SCALE-${this.facts.length + 1}`,
          statement: `مقیاس استخراج‌شده از تحلیل متن آزاد: ${slots.scale}`
        });
      }
      if (slots.geography && !this.phaseData[1].geographyFromFreeform) {
        this.phaseData[1].geographyFromFreeform = slots.geography;
        this.facts.push({
          id: `FACT-FREEFORM-GEO-${this.facts.length + 1}`,
          statement: `محدوده جغرافیایی استخراج‌شده از تحلیل متن آزاد: ${slots.geography}`
        });
      }
      if (slots.primaryBottleneck && !this.phaseData[1].primaryBottleneck) {
        this.phaseData[1].primaryBottleneck = slots.primaryBottleneck;
        this.facts.push({
          id: `FACT-FREEFORM-PAIN-${this.facts.length + 1}`,
          statement: `گلوگاه عملیاتی شناسایی‌شده از متن آزاد: ${slots.primaryBottleneck}`
        });
      }
    }

    // Record data into phaseData
    if (this.phaseData[phase]) {
      this.phaseData[phase][qId] = userText;
      if (optionValue) this.phaseData[phase][`${qId}Value`] = optionValue;
    }

    if (phase === 1) {
      const isStageValue = ["active", "idea", "pre_launch", "rebrand"].includes(optionValue);
      const isGeoValue = ["local_city", "nationwide_iran", "international", "city_regional"].includes(optionValue);
      const legacyDescValues = [
        "local_automotive_service",
        "hospitality_cafe_roastery",
        "industrial_manufacturing",
        "b2b_saas_software",
        "creator_coaching_personal",
        "ecommerce_products"
      ];
      const isDescValue =
        legacyDescValues.includes(optionValue) ||
        (typeof optionValue === "string" && (optionValue.startsWith("BT-") || optionValue.startsWith("bt-") || optionValue === "custom")) ||
        (userText && (userText.includes("صنف انتخابی:") || (qId === "step0_description" && !isStageValue && !isGeoValue)));

      if (isStageValue || (qId === "step0_stage" && !isDescValue && !isGeoValue)) {
        this.phaseData[1].stage = userText;
        if (optionValue) this.phaseData[1].stageValue = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `مرحله فعلی: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else if (isDescValue || (qId === "step0_description" && !isStageValue && !isGeoValue)) {
        this.phaseData[1].description = userText;
        if (optionValue) this.phaseData[1].descriptionValue = optionValue;
        if (typeof optionValue === "string" && optionValue.toUpperCase().startsWith("BT-")) {
          this.phaseData[1].taxonomyId = optionValue.toUpperCase();
        }
        if (slots?.businessTypeMatch && !this.phaseData[1].descriptionValue) {
          this.phaseData[1].descriptionValue = slots.businessTypeMatch.id;
          this.phaseData[1].taxonomyId = slots.businessTypeMatch.id;
        }
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `صنف و مدل فعالیت: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else if (qId === "step0_diagnostic_probing") {
        const isLegacyDesc =
          legacyDescValues.includes(optionValue) ||
          (typeof optionValue === "string" && (optionValue.startsWith("BT-") || optionValue.startsWith("bt-") || optionValue === "custom" || optionValue.trim() === ""));

        if (isLegacyDesc) {
          // Caller passed description answer directly (legacy test flow bypassing diagnostic probe)
          this.phaseData[1].description = userText;
          if (optionValue) this.phaseData[1].descriptionValue = optionValue;
          this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `صنف و مدل فعالیت: ${userText}` });
          this.businessContext = classifyBusinessContext(this.phaseData);
          // Advance past step0_description so next question is step0_geography
          this.currentStepIndex++;
        } else {
          this.phaseData[1].diagnosticVision = userText;
          if (optionValue) this.phaseData[1].diagnosticVisionValue = optionValue;
          this.facts.push({
            id: "FACT-FOUNDER-VISION",
            statement: `دیدگاه و هویت بنیان‌گذار: ${userText}`
          });
          if (slots?.businessTypeMatch && !this.phaseData[1].descriptionValue) {
            this.phaseData[1].resolvedBT = slots.businessTypeMatch;
          }
          this.businessContext = classifyBusinessContext(this.phaseData);
        }
      } else if (isGeoValue || qId === "step0_geography") {
        this.phaseData[1].geography = userText;
        if (optionValue) this.phaseData[1].geographyValue = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `محدوده جغرافیایی: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else if (qId === "step1_primary_goal") {
        this.phaseData[1].primaryGoal = userText;
        if (optionValue) this.phaseData[1].primaryGoalValue = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `${currentQ?.title || "هدف ملموس"}: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else if (qId === "step2_core_offer") {
        this.phaseData[1].coreOffer = userText;
        if (optionValue) this.phaseData[1].coreOfferValue = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `${currentQ?.title || "پیشنهاد اصلی"}: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else if (qId === "step2_value_hypothesis") {
        this.phaseData[1].valueHypothesis = userText;
        if (optionValue) this.phaseData[1].valueHypothesisValue = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `${currentQ?.title || "فرضیه تمایز"}: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      } else {
        this.phaseData[1][qId] = userText;
        if (optionValue) this.phaseData[1][`${qId}Value`] = optionValue;
        this.facts.push({ id: `F-P1-${this.facts.length + 1}`, statement: `${currentQ?.title || qId}: ${userText}` });
        this.businessContext = classifyBusinessContext(this.phaseData);
      }
    } else if (phase === 2) {
      if (qId === "p2_step0_competitors") this.phaseData[2].competitors = userText;
      else if (qId === "p2_step1_customer_pain") this.phaseData[2].customerPain = userText;
      else if (qId === "p2_step2_pricing_models") this.phaseData[2].pricingModel = userText;
      else if (qId === "p2_step3_primary_channel") this.phaseData[2].primaryChannel = userText;
      else if (qId === "p2_step4_golden_opportunity") this.phaseData[2].goldenOpportunity = userText;
      this.decisions.push({ id: `D-P2-${this.decisions.length + 1}`, statement: `${currentQ?.title || "تحلیل"}: ${userText}` });
    } else if (phase === 3) {
      if (qId === "p3_target_segment") this.phaseData[3].targetSegment = userText;
      else if (qId === "p3_positioning_frame") this.phaseData[3].positioning = userText;
      else if (qId === "p3_strategic_boundary") this.phaseData[3].boundary = userText;
      else if (qId === "p3_brand_promise") this.phaseData[3].promise = userText;
      this.decisions.push({ id: `D-P3-${this.decisions.length + 1}`, statement: `استراتژی ${currentQ?.title}: ${userText}` });
    } else if (phase === 4) {
      if (qId === "p4_archetype") this.phaseData[4].archetype = userText;
      else if (qId === "p4_human_traits") this.phaseData[4].traits = userText;
      else if (qId === "p4_tone_guardrail") this.phaseData[4].toneGuardrail = userText;
      this.facts.push({ id: `F-P4-${this.facts.length + 1}`, statement: `هویت ${currentQ?.title}: ${userText}` });
    } else if (phase === 5) {
      if (qId === "p5_voice_style") this.phaseData[5].voiceStyle = userText;
      else if (qId === "p5_elevator_hook") this.phaseData[5].elevatorHook = userText;
      else if (qId === "p5_forbidden_words") this.phaseData[5].forbiddenWords = userText;
      this.decisions.push({ id: `D-P5-${this.decisions.length + 1}`, statement: `کلام ${currentQ?.title}: ${userText}` });
    } else if (phase === 6) {
      if (qId === "p6_naming_territory") this.phaseData[6].naming = userText;
      else if (qId === "p6_tagline_archetype") this.phaseData[6].tagline = userText;
      this.decisions.push({ id: `D-P6-${this.decisions.length + 1}`, statement: `نام و شعار: ${userText}` });
    } else if (phase === 7) {
      if (qId === "p7_color_palette") this.phaseData[7].colorPalette = userText;
      else if (qId === "p7_typography_mood") this.phaseData[7].typography = userText;
      else if (qId === "p7_logo_direction") this.phaseData[7].logoConcept = userText;
      this.decisions.push({ id: `D-P7-${this.decisions.length + 1}`, statement: `هویت بصری: ${userText}` });
    } else if (phase === 8) {
      if (qId === "p8_thought_leadership") this.phaseData[8].thoughtLeadership = userText;
      else if (qId === "p8_pr_podcast_channels") this.phaseData[8].prChannels = userText;
      else if (qId === "p8_lead_funnel") this.phaseData[8].leadFunnel = userText;
      else if (qId === "p8_crisis_reputation") this.phaseData[8].reputationCrisis = userText;
      this.decisions.push({ id: `D-P8-${this.decisions.length + 1}`, statement: `فعال‌سازی ${currentQ?.title}: ${userText}` });
    }

    // Invalidate current phase completion upon re-editing answers
    if (this.completedPhases[phase]) {
      this.completedPhases[phase] = false;
    }

    // Downstream Invalidation Trigger: If any upstream phase is modified while downstream phases are completed
    let hasDownstreamCompleted = false;
    for (let k = phase + 1; k <= 8; k++) {
      if (this.completedPhases[k]) {
        hasDownstreamCompleted = true;
        break;
      }
    }
    if (hasDownstreamCompleted) {
      this.invalidateDependentPhases(phase);
    }

    // Detect semantic & factual contradictions across project state
    const detectedContradictions = ContradictionEngine.detectContradictions(this);
    detectedContradictions.forEach(c => {
      const exists = this.contradictions.some(
        existing => existing.statementA === c.statementA && existing.statementB === c.statementB
      );
      if (!exists) {
        this.contradictions.push(c);
      }
    });

    this.currentStepIndex++;
    const nextQ = this.getCurrentQuestion();

    if (nextQ) {
      return {
        reply: `ثبت شد! داده با موفقیت در پرونده فاز ${phase} ذخیره گردید. ✔️\n\n${nextQ.text}`,
        nextQuestion: nextQ,
        isCompleted: false
      };
    } else {
      return this.finalizeCurrentPhase();
    }
  }

  getPhaseName(p) {
    const phaseNames = {
      1: "کشف و بنیاد کسب‌وکار",
      2: "هوش بازار و پژوهش مشتری",
      3: "استراتژی و جهت‌گیری برند",
      4: "هویت و شخصیت برند",
      5: "سیستم هویت کلامی و پیام‌رسانی",
      6: "نام‌گذاری، شعار و جهت‌گیری خلاقانه",
      7: "سیستم طراحی هویت بصری",
      8: "برنامه فعال‌سازی اجرایی، PR و مدیریت اعتبار"
    };
    return phaseNames[p] || `فاز ${p}`;
  }

  finalizeCurrentPhase() {
    const p = this.currentPhase;

    if (p === 1) {
      this.businessContext = classifyBusinessContext(this.phaseData);
    }

    // Real Phase Gate Validation (Requirement R2)
    const gateResult = validatePhaseGate(p, this);

    if (!gateResult.passed) {
      this.completedPhases[p] = false;
      const reasonsList = gateResult.blockingReasons.map(r => `- ❌ ${r}`).join("\n");
      const missingList = gateResult.missingFacts.length > 0
        ? `\n\n📌 **اقلام اطلاعاتی مفقود:**\n` + gateResult.missingFacts.map(f => `- ⚠️ ${f}`).join("\n")
        : "";

      return {
        reply: `🛑 **توقف در گیت خروج فاز ${p} (${this.getPhaseName(p)})**\n\nامکان نهایی‌سازی فاز جاری وجود ندارد زیرا الزامات ورود به مرحله بعد محقق نشده است:\n\n${reasonsList}${missingList}\n\n💡 *لطفاً موارد فوق را شفاف‌سازی کنید تا امکان عبور از گیت و صدور سند فراهم شود.*`,
        nextQuestion: null,
        isCompleted: false,
        gatePassed: false,
        gateResult: gateResult,
        completedPhase: null,
        nextPhase: null,
        isFinalGrandFinale: false
      };
    }

    this.completedPhases[p] = true;
    if (this.phaseStatus[p] === "INVALIDATED") {
      delete this.phaseStatus[p];
    }

    const phaseNames = {
      1: "کشف و بنیاد کسب‌وکار",
      2: "هوش بازار و پژوهش مشتری",
      3: "استراتژی و جهت‌گیری برند",
      4: "هویت و شخصیت برند",
      5: "سیستم هویت کلامی و پیام‌رسانی",
      6: "نام‌گذاری، شعار و جهت‌گیری خلاقانه",
      7: "سیستم طراحی هویت بصری",
      8: "برنامه فعال‌سازی اجرایی، PR و مدیریت اعتبار"
    };

    if (p < 8) {
      return {
        reply: `🎉 **تبریک می‌گویم! تمامی مراحل فاز ${p} (${phaseNames[p]}) با موفقیت تکمیل شد.**\n\nگیت اعتبارسنجی با نمره شواهد ${gateResult.evidenceScore}/100 تایید شد و سند تخصصی صادر گردید.\n\n👇 **روی دکمه «ورود به فاز ${p + 1}: ${phaseNames[p + 1]}» کلیک کنید تا ادامه دهیم:**`,
        nextQuestion: null,
        isCompleted: true,
        gatePassed: true,
        gateResult: gateResult,
        completedPhase: p,
        nextPhase: p + 1,
        isFinalGrandFinale: false
      };
    } else {
      return {
        reply: `🏆 **شاهکار است! تبریک صمیمانه، شما تمامی ۸ فاز برندینگ و فعال‌سازی اجرایی را با موفقیت ۱۰۰٪ نهایی کردید!**\n\nاکنون کل هویت برند، تمایز محوری، کاراکتر، پیام‌رسانی، نام، سیستم بصری و ماشین فعال‌سازی تجاری و سئوی شما به صورت علمی و هماهنگ تدوین شد.\n\n🌟 **«کتابچه جامع استراتژی و ماشین اجرای برند (Master Brand Book & Execution Machine)»** شامل تمامی اسناد ۸ گانه تولید شده و آماده دانلود یکپارچه است!`,
        nextQuestion: null,
        isCompleted: true,
        gatePassed: true,
        gateResult: gateResult,
        completedPhase: 8,
        nextPhase: null,
        isFinalGrandFinale: true
      };
    }
  }

  generateDeliverableData(phaseNum = this.currentPhase) {
    return generateDeliverable(phaseNum, this.phaseData, this.businessContext, this.decisions, this.facts, this.unknowns);
  }

  generateMarkdownText(phaseNum = this.currentPhase) {
    const data = this.generateDeliverableData(phaseNum);
    let md = `# ${data.title}\n\n`;
    md += `**فاز:** ${data.phase}  \n`;
    md += `**نسخه:** ${data.version}  \n`;
    md += `**تاریخ ثبت:** ${data.date}  \n\n`;
    md += `---\n\n`;

    data.sections.forEach(sec => {
      md += `## ${sec.title}\n\n`;
      if (sec.content && typeof sec.content === "object") {
        Object.entries(sec.content).forEach(([k, v]) => {
          md += `- **${k}:** ${v}\n`;
        });
        md += `\n`;
      }
      if (sec.flowchart) {
        md += `\`\`\`text\n${sec.flowchart.trim()}\n\`\`\`\n\n`;
      }
      if (Array.isArray(sec.checklist)) {
        sec.checklist.forEach(chk => {
          md += `- [ ] ${chk}\n`;
        });
        md += `\n`;
      }
      if (Array.isArray(sec.formulas)) {
        md += `### فرمول‌های محاسباتی:\n`;
        sec.formulas.forEach(f => {
          md += `- **${f.name}:** \`${f.formula}\` — *${f.description}*\n`;
        });
        md += `\n`;
      }
      if (Array.isArray(sec.kpis)) {
        md += `### جدول سنجه‌ها و آستانه‌های ارزیابی (KPIs):\n\n`;
        md += `| شاخص | فرمول / مبنا | هدف مطلوب (سبز) | هشدار (زرد) | بحران (قرمز) |\n`;
        md += `|---|---|---|---|---|\n`;
        sec.kpis.forEach(k => {
          md += `| ${k.metric} | ${k.formula} | ${k.green} | ${k.yellow} | ${k.red} |\n`;
        });
        md += `\n`;
      }
      if (Array.isArray(sec.items)) {
        sec.items.forEach(it => {
          md += `- ${it}\n`;
        });
      }
      md += `\n`;
    });

    return md;
  }
}
