import { classifyBusinessContext, getPhaseAdaptationRules } from "../data/businessContextRouter.js";
import { INTERVIEW_FIELDS, FIELD_BY_QUESTION, UNKNOWN_ANSWER, activeAnswers, migrateAnswerRecords } from "./interviewSchema.js";
import { validateQuestionAdaptation } from "./adaptiveInterview.js";
import { generateDeliverable, deliverableToMarkdown } from './deliverableGenerator.js';
import { composeChainedQuestions } from './dynamicQuestionEngine.js';
import { detectUnknownIntent, parseSemanticInput } from './semanticParser.js';
import { validatePhaseGate } from "./phaseGateValidator.js";
import { UnknownsManager, UNKNOWN_STATUS } from "./unknownsManager.js";
import { ContradictionEngine, CONTRADICTION_STATUS } from "./contradictionEngine.js";

/**
 * 4-State Lifecycle for AI-generated dynamic questions (Requirement R13, Feature 10)
 */
export const DYNAMIC_QUESTION_STATE = {
  PENDING: "PENDING",     // Generated by AI Brain, ready to be presented
  ACTIVE: "ACTIVE",       // Currently displayed to user as current question
  CONSUMED: "CONSUMED",   // User has answered; state recorded
  ARCHIVED: "ARCHIVED"    // Retired to history, cannot cause repeat loops
};

export class OrchestratorEngine {
  constructor() {
    this.currentPhase = 1;
    this.currentStepIndex = 0;
    this.isNavigatingBack = false;
    this.reviewCursor = null;

    this.completedPhases = {
      1: false, 2: false, 3: false, 4: false, 5: false, 6: false, 7: false, 8: false
    };

    this.phaseStatus = {};

    // Store responses across all 8 phases
    this.phaseData = {
      1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}
    };

    this.facts = [];
    this.decisions = [];
    this.assumptions = [];
    this.unknowns = [];
    this.contradictions = [];
    this.businessContext = null;
    this.revision = 0;
    this.answerRecords = [];
    this.aiInsights = [];
    this.reviewRequired = {};
    this.lastGateResult = null;

    // 4-state dynamic question lifecycle state machine
    this.dynamicQuestion = null; // { id, title, text, whyItMatters, options, state, createdAt, source }
    this.dynamicQuestionState = null;
    this.dynamicQuestionsHistory = [];
    this.dynamicQuestionOverride = null; // legacy backwards-compatible alias
  }

  setBusinessContext(context) {
    this.businessContext = context;
    this.revision++;
  }

  setContext(context) {
    this.setBusinessContext(context);
  }

  addStrategicDecision(statement) {
    // Model suggestions are proposals, never user-approved decisions.
    if (typeof statement !== 'string' || !statement.trim()) return;
    this.aiInsights.push({ proposedDecision: statement.trim(), status: 'PROPOSED', revision: this.revision });
  }

  createAITurn() {
    const next = this.getCurrentQuestion();
    return {
      revision: this.revision, phase: this.currentPhase,
      questionId: next?.id || null,
      snapshot: JSON.parse(JSON.stringify({
        phaseNum: this.currentPhase, context: this.businessContext,
        priorAnswers: this.phaseData, facts: this.facts, decisions: this.decisions,
        answerRecords: activeAnswers(this.answerRecords), unknowns: this.unknowns,
        contradictions: this.contradictions, targetQuestion: next,
      })),
    };
  }

  applyAIResult(turn, result) {
    if (!turn || turn.revision !== this.revision || turn.phase !== this.currentPhase) return false;
    const target = this.getCurrentQuestion();
    if (!target || target.id !== turn.questionId) return false;
    const question = validateQuestionAdaptation(result?.nextQuestion, target);
    if (!question) return false;
    this.aiInsights.push({
      analysisSummary: result.analysisSummary || '', proposedDecision: result.extractedDecision || null,
      status: 'PROPOSED', revision: this.revision,
      answerId: this.answerRecords.at(-1)?.id, phase: this.currentPhase,
    });
    return Boolean(this.setDynamicNextQuestion({ ...question, id: `ai-${target.id}-r${this.revision}` }));
  }

  selectGuild(guild) {
    if (!guild?.id || !guild?.titleFa) return;
    this.clearDynamicQuestion();
    this.currentPhase = 1;
    this.reviewCursor = null;
    this.currentStepIndex = 0;
    this.isNavigatingBack = false;
    return this.processUserResponse(`صنف انتخابی: ${guild.titleFa}`, guild.id, { questionId: 'step0_description' });
  }

  /**
   * Enqueues a dynamic AI question using the 4-state lifecycle state machine.
   * Protects against infinite loops, stale overrides, and repeat questions.
   */
  setDynamicNextQuestion(question) {
    if (!question || (!question.text && !question.title)) return null;
    const qId = question.id || `dynamic_q_${Date.now()}`;

    // Loop protection: check if identical question already archived
    const isDuplicate = this.dynamicQuestionsHistory.some(
      h => h.id === qId || (h.text && question.text && h.text.trim() === question.text.trim())
    );
    if (isDuplicate) {
      console.warn(`[DynamicQuestionEngine] Duplicate dynamic question '${qId}' rejected to prevent loops.`);
      return null;
    }

    const dynRecord = {
      ...question,
      id: qId,
      state: DYNAMIC_QUESTION_STATE.PENDING,
      createdAt: new Date().toISOString(),
      source: question.source || 'KNOWLEDGE_BRAIN_AI'
    };

    this.dynamicQuestion = dynRecord;
    this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.PENDING;

    // Legacy backwards-compatible mirror
    this.dynamicQuestionOverride = {
      question: dynRecord,
      consumed: false,
      createdAt: dynRecord.createdAt,
      source: dynRecord.source
    };

    return dynRecord;
  }

  getDynamicQuestionState() {
    return this.dynamicQuestionState;
  }

  getDynamicQuestionsHistory() {
    return [...this.dynamicQuestionsHistory];
  }

  clearDynamicQuestion() {
    if (this.dynamicQuestion) {
      this.dynamicQuestionsHistory.push({
        ...this.dynamicQuestion,
        state: DYNAMIC_QUESTION_STATE.ARCHIVED,
        cancelledAt: new Date().toISOString()
      });
    }
    this.dynamicQuestion = null;
    this.dynamicQuestionState = null;
    this.dynamicQuestionOverride = null;
  }

  getCurrentPhaseQuestions() {
    const questions = composeChainedQuestions(
      this.currentPhase,
      this.businessContext,
      this.phaseData,
      this.unknowns,
      this.phaseData[1]?.diagnosticVision || ""
    );
    const review = this.reviewRequired[this.currentPhase] || [];
    return questions.map(q => review.includes(q.id) ? { ...q, isAnswered: false, needsReview: true } : q);
  }

  getCurrentQuestion() {
    // Dynamic question lifecycle check (PENDING -> ACTIVE)
    if (this.dynamicQuestion) {
      if (this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.PENDING || this.dynamicQuestion.state === DYNAMIC_QUESTION_STATE.ACTIVE) {
        this.dynamicQuestion.state = DYNAMIC_QUESTION_STATE.ACTIVE;
        this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.ACTIVE;
        return this.dynamicQuestion;
      }
    } else if (this.dynamicQuestionOverride && !this.dynamicQuestionOverride.consumed) {
      return this.dynamicQuestionOverride.question;
    }
    const questions = this.getCurrentPhaseQuestions();
    if (!questions || questions.length === 0) return null;
    if (!this.isNavigatingBack && this.reviewCursor === null) {
      const conflict = ContradictionEngine.getBlockingContradictions(this.contradictions, this.currentPhase)
        .find(c => c.resolutionTargets?.[this.currentPhase]);
      const targetId = conflict?.resolutionTargets?.[this.currentPhase];
      const target = questions.find(q => q.id === targetId);
      if (target) return {
        ...target, isAnswered: false, isDynamic: true, resolutionFor: conflict.id,
        text: `${conflict.resolutionQuestion}\n\nپاسخ قبلی شما: «${this.phaseData[this.currentPhase]?.[targetId] || this.phaseData[this.currentPhase]?.[FIELD_BY_QUESTION[targetId]?.field] || ''}»\n${target.text}`,
      };
    }

    // If user explicitly navigated back, return the question at currentStepIndex
    if ((this.isNavigatingBack || this.reviewCursor !== null) && this.currentStepIndex >= 0 && this.currentStepIndex < questions.length) {
      return questions[this.currentStepIndex];
    }

    // Check if all questions in the current phase are already answered
    const hasUnanswered = questions.some(q => q && !q.isAnswered);
    if (!hasUnanswered) {
      return null;
    }

    // Dynamically find the first question in the current phase that has not been answered yet!
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      if (q && !q.isAnswered) {
        this.currentStepIndex = i;
        return q;
      }
    }

    return null;
  }

  /**
   * Navigates back to the previous question in the current phase
   */
  navigateBack() {
    this.clearDynamicQuestion();
    this.revision++;
    const questions = this.getCurrentPhaseQuestions();
    if (!questions || this.currentStepIndex <= 0) return null;
    this.currentStepIndex = Math.max(0, this.currentStepIndex - 1);
    this.isNavigatingBack = true;
    if (questions[this.currentStepIndex]) {
      questions[this.currentStepIndex].isAnswered = false;
    }
    return this.getCurrentQuestion();
  }

  canStartPhase(phaseNum) {
    if (typeof phaseNum !== "number" && typeof phaseNum !== "string") {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    if (Array.isArray(phaseNum)) {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    if (typeof phaseNum === "string" && phaseNum.trim() === "") {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }
    const p = Number(phaseNum);
    if (isNaN(p) || !Number.isInteger(p) || p < 1 || p > 8) {
      return {
        allowed: false,
        reason: `شماره فاز نامعتبر است (${phaseNum}). فازها باید عددی بین ۱ تا ۸ باشند.`
      };
    }

    if (p === 1) {
      return { allowed: true };
    }

    // Phase N can ONLY be opened if Phase N-1 has passed its exit gate
    if (!this.completedPhases[p - 1]) {
      return {
        allowed: false,
        reason: `ورود به فاز ${p} مجاز نیست. فاز پیش‌نیاز ${p - 1} هنوز تکمیل و تایید نشده است. سیستم دیجیتال مارکت از پرش فازها جلوگیری می‌کند.`
      };
    }

    // Check all earlier phases 1 to p-2 as well
    for (let prev = 1; prev < p - 1; prev++) {
      if (!this.completedPhases[prev]) {
        return {
          allowed: false,
          reason: `ورود به فاز ${p} مجاز نیست. فاز اولیه ${prev} تایید نشده یا ابطال گردیده است.`
        };
      }
    }

    return { allowed: true };
  }

  getPhaseStatus(phaseNum) {
    if (typeof phaseNum !== "number" && typeof phaseNum !== "string") return "INVALID";
    if (Array.isArray(phaseNum)) return "INVALID";
    if (typeof phaseNum === "string" && phaseNum.trim() === "") return "INVALID";
    const p = Number(phaseNum);
    if (isNaN(p) || !Number.isInteger(p) || p < 1 || p > 8) return "INVALID";

    if (this.phaseStatus[p] === "INVALIDATED") {
      return "INVALIDATED";
    }

    if (this.completedPhases[p] === true) {
      return "COMPLETED";
    }

    if (this.currentPhase === p) {
      return "IN_PROGRESS";
    }

    const canStart = this.canStartPhase(p);
    if (canStart.allowed) {
      return "AVAILABLE";
    }

    return "LOCKED";
  }

  invalidateDependentPhases(fromPhase) {
    const p = Number(fromPhase);
    const invalidated = [];

    if (p >= 1 && p < 8) {
      for (let ph = p + 1; ph <= 8; ph++) {
        const hadData = this.completedPhases[ph] || Object.keys(this.phaseData[ph] || {}).length > 0;
        if (this.completedPhases[ph]) {
          this.completedPhases[ph] = false;
          invalidated.push(ph);
        }
        if (!hadData) continue;
        this.phaseStatus[ph] = "INVALIDATED";
        this.reviewRequired[ph] = INTERVIEW_FIELDS.filter(spec => spec.phase === ph &&
          (this.phaseData[ph]?.[spec.field] || this.phaseData[ph]?.[spec.questionId])).map(spec => spec.questionId);
      }
    }

    const message = invalidated.length > 0
      ? `⚠️ **هشدار ابطال فازهای وابسته:** با توجه به تغییر اطلاعات بنیادین در فاز ${p}، خروجی‌های وابسته در فازهای (${invalidated.join("، ")}) نامعتبر شده و نیازمند بازبینی مجدد هستند.`
      : `هیچ فاز تکمیلی وابسته‌ای نیاز به ابطال نداشت.`;

    return {
      fromPhase: p,
      invalidatedPhases: invalidated,
      message
    };
  }

  getQuestionByIndex(index) {
    const questions = this.getCurrentPhaseQuestions();
    const idx = Math.max(0, Math.min(index, questions.length - 1));
    return questions[idx] || null;
  }

  previousQuestion() {
    this.clearDynamicQuestion();
    this.revision++;
    const questions = this.getCurrentPhaseQuestions();
    if (this.currentStepIndex > 0) {
      this.currentStepIndex--;
    }
    this.isNavigatingBack = true;
    return questions[this.currentStepIndex] || null;
  }

  goToQuestion(index) {
    this.clearDynamicQuestion();
    this.revision++;
    const questions = this.getCurrentPhaseQuestions();
    const idx = Math.max(0, Math.min(index, questions.length - 1));
    this.currentStepIndex = idx;
    this.isNavigatingBack = true;
    return questions[idx] || null;
  }

  // Controlled transition to phase (1 to 8) enforcing anti-skip protocol
  startPhase(phaseNum) {
    const check = this.canStartPhase(phaseNum);
    if (!check.allowed) {
      const err = new Error(check.reason);
      err.isGateBlocked = true;
      err.phase = phaseNum;
      throw err;
    }

    this.clearDynamicQuestion();
    this.revision++;
    phaseNum = Number(phaseNum);
    this.currentPhase = phaseNum;
    this.reviewCursor = null;
    this.currentStepIndex = 0;
    this.isNavigatingBack = false;


    const offer = this.phaseData[1]?.coreOffer || this.phaseData[1]?.description || "خدمات و تخصص محوری";
    const seg = this.phaseData[3]?.targetSegment || "مشتریان ارزش‌محور";
    const char = this.phaseData[4]?.archetype || "رفیق کاربلد و راهنما";
    const voice = this.phaseData[5]?.voiceStyle || "صمیمی و حرفه‌ای";
    const name = this.phaseData[6]?.naming || "برند تخصصی";

    let handoffMsg = "";

    if (phaseNum === 2) {
      handoffMsg = `🔍 **ورود به فاز ۲: هوش بازار و پژوهش مشتری (Market Intelligence)**\n\n` +
        `اطلاعات فاز ۱ به همراه بافتار شناسایی‌شده صنف شما ثبت شد:\n` +
        `- 📌 **صنف و پیشنهاد اصلی:** ${offer}\n` +
        `- 🎯 **آرکی‌تایپ بافتار:** ${this.businessContext?.archetypeTitle || "کسب‌وکار تخصصی"}\n\n` +
        `اکنون تحلیل رقبا، دغدغه و درد مشتریان و فرصت‌های طلایی تمایز را بررسی می‌کنیم:`;
    } else if (phaseNum === 3) {
      handoffMsg = `🎯 **ورود به فاز ۳: استراتژی و جهت‌گیری برند (Brand Strategy)**\n\n` +
        `شواهد هوش بازار فاز ۲ تحویل شد:\n` +
        `- 💡 **درد اصلی بازار:** ${this.phaseData[2]?.customerPain || "کیفیت پایین و عدم همراهی"}\n` +
        `- 🌟 **فرصت طلایی تمایز:** ${this.phaseData[2]?.goldenOpportunity || "سادگی و ضمانت واقعی"}\n\n` +
        `حالا این شواهد را به انتخاب‌های استراتژیک، جایگاه‌یابی منحصربه‌فرد و وعده برند تبدیل می‌کنیم:`;
    } else if (phaseNum === 4) {
      handoffMsg = `✨ **ورود به فاز ۴: هویت و شخصیت برند (Brand Character)**\n\n` +
        `بنیاد استراتژی فاز ۳ تحویل شد:\n` +
        `- 🎯 **بخش هدف:** ${seg}\n` +
        `- 🛡️ **جایگاه تمایز:** ${this.phaseData[3]?.positioning || "ارائه باکیفیت و بدون دردسر"}\n\n` +
        `حالا استراتژی را به یک کاراکتر انسانی ملموس با کهن‌الگو و صفات رفتاری متمایز تبدیل می‌کنیم:`;
    } else if (phaseNum === 5) {
      handoffMsg = `🗣️ **ورود به فاز ۵: سیستم هویت کلامی و پیام‌رسانی (Verbal Identity)**\n\n` +
        `کاراکتر فاز ۴ تحویل شد:\n` +
        `- 🎭 **کهن‌الگو:** ${char}\n` +
        `- 💎 **صفات رفتاری:** ${this.phaseData[4]?.traits || "صادق، دقیق و متعهد"}\n\n` +
        `اکنون صدای برند، لحن، قلاب معرفی آسانسوری ۳۰ ثانیه‌ای و واژگان ممنوعه را طراحی می‌کنیم:`;
    } else if (phaseNum === 6) {
      handoffMsg = `🔥 **ورود به فاز ۶: نام‌گذاری، شعار و جهت‌گیری خلاقانه (Naming & Creative Direction)**\n\n` +
        `هویت کلامی فاز ۵ تحویل شد:\n` +
        `- 📢 **سبک صدا:** ${voice}\n` +
        `- 🎯 **قلاب معرفی:** ${this.phaseData[5]?.elevatorHook || "حل مستقیم درد مخاطب"}\n\n` +
        `حالا قلمرو نام‌گذاری، سبک شعار محوری و بریف دیزاین را مشخص می‌کنیم:`;
    } else if (phaseNum === 7) {
      handoffMsg = `🎨 **ورود به فاز ۷: طراحی سیستم هویت بصری (Visual Identity Design System)**\n\n` +
        `نام و شعار فاز ۶ تحویل شد:\n` +
        `- 🏷️ **نام برند:** ${name}\n` +
        `- ⚡ **شعار:** ${this.phaseData[6]?.tagline || "تعهد پایدار به کیفیت و رضایت"}\n\n` +
        `در این فاز، پالت رنگی روان‌شناختی، تایپوگرافی فارسی و فرم نشان بصری را انتخاب می‌کنیم:`;
    } else if (phaseNum === 8) {
      handoffMsg = `🚀 **ورود به فاز ۸: برنامه فعال‌سازی اجرایی و مدیریت اعتبار (Executive Activation & Reputation)**\n\n` +
        `سیستم کامل ۷ فاز قبلی با موفقیت تصویب شد:\n` +
        `- 🏷️ **نام و هویت برند:** ${name}\n` +
        `- 🎯 **جایگاه و بخش هدف:** ${seg}\n` +
        `- 📢 **سبک پیام و صدا:** ${voice}\n\n` +
        `اکنون برند طراحی‌شده را وارد میدان عملیات می‌کنیم: سئوی محلی/شخصی، رسانه‌ها، قیف تجاری و پروتکل حل بحران:`;
    }

    const adaptationRule = getPhaseAdaptationRules(phaseNum, this.businessContext);
    if (adaptationRule && adaptationRule.instruction) {
      handoffMsg += `\n\n🎯 **انطباق تخصصی بافتار صنف (${this.businessContext?.archetypeTitle || ""}):**\n${adaptationRule.instruction}`;
    }

    const firstQ = this.getCurrentQuestion();
    return {
      welcomeMessage: handoffMsg,
      firstQuestion: firstQ
    };
  }

  processUserResponse(userText, optionValue = null, options = {}) {
    if (typeof userText !== 'string' || !userText.trim()) return { reply: 'پاسخ خالی قابل ثبت نیست.', nextQuestion: this.getCurrentQuestion(), isCompleted: false, accepted: false };
    userText = userText.trim();
    const displayed = this.getCurrentQuestion();
    if (options.expectedQuestionId && displayed?.id !== options.expectedQuestionId) {
      throw new Error('سؤال تغییر کرده است؛ پاسخ را برای سؤال فعلی ثبت کنید.');
    }
    let currentQ = displayed;
    let qId = options.questionId || currentQ?.baseQuestionId || currentQ?.id;
    // Legacy callers can select a guild or stage without stepping through the UI.
    if (!options.expectedQuestionId && !currentQ?.baseQuestionId && this.currentPhase === 1 && typeof optionValue === 'string' && (/^BT-\d+$/i.test(optionValue) ||
        ['local_automotive_service', 'hospitality_cafe_roastery', 'industrial_manufacturing',
         'b2b_saas_software', 'creator_coaching_personal', 'health_beauty_wellness', 'ecommerce_products'].includes(optionValue))) qId = 'step0_description';
    else if (!options.expectedQuestionId && !currentQ?.baseQuestionId && this.currentPhase === 1 && ['active', 'idea', 'pre_launch', 'rebrand'].includes(optionValue)) qId = 'step0_stage';
    else if (!options.expectedQuestionId && !currentQ?.baseQuestionId && this.currentPhase === 1 && ['local_city', 'nationwide_iran', 'international', 'city_regional'].includes(optionValue)) qId = 'step0_geography';
    if (!qId) return { reply: 'سؤالی برای این پاسخ انتخاب نشده است.', nextQuestion: null, isCompleted: Boolean(this.completedPhases[this.currentPhase]), accepted: false };
    const spec = FIELD_BY_QUESTION[qId];
    const phase = spec?.phase || this.currentPhase;
    if (phase !== this.currentPhase && !options.questionId) {
      throw new Error('این پاسخ متعلق به فاز جاری نیست.');
    }
    if (this.dynamicQuestion) {
      this.dynamicQuestionsHistory.push({ ...this.dynamicQuestion,
        state: DYNAMIC_QUESTION_STATE.ARCHIVED, userAnswer: userText, optionValue,
        answeredAt: new Date().toISOString() });
      this.dynamicQuestion = null;
      this.dynamicQuestionState = DYNAMIC_QUESTION_STATE.ARCHIVED;
      this.dynamicQuestionOverride = null;
    }
    const reviewing = this.isNavigatingBack || this.reviewCursor !== null;
    this.isNavigatingBack = false;
    if (!this.answerRecords.length) this.answerRecords = migrateAnswerRecords(this.phaseData);
    const previous = activeAnswers(this.answerRecords).find(a => a.phase === phase && a.questionId === qId);
    const field = spec?.field || qId;
    const oldValue = this.phaseData[phase]?.[field];
    this.revision++;
    const unknownIntent = detectUnknownIntent(userText);
    const unknown = optionValue === 'unknown' || unknownIntent.isUnknown;
    const estimate = /حدود|تقریب|برآورد|حدس|احتمال|فکر می.کنم/.test(userText);
    const record = {
      id: `ANS-${this.revision}`, revision: this.revision, phase, questionId: qId, field,
      label: spec?.label || currentQ?.title || qId,
      presentedQuestionId: currentQ?.id || qId,
      questionText: (qId === currentQ?.id || qId === currentQ?.baseQuestionId ? currentQ?.text : spec?.label) || qId,
      text: userText, optionValue,
      kind: unknown ? 'UNKNOWN' : estimate ? 'ASSUMPTION' : (spec?.kind || 'FACT'),
      status: 'ACTIVE', source: optionValue ? 'USER_OPTION' : 'USER_TEXT',
      createdAt: new Date().toISOString(),
    };
    if (previous) { previous.status = 'SUPERSEDED'; previous.supersededBy = record.id; }
    this.answerRecords.push(record);
    const data = this.phaseData[phase] ||= {};
    const storedText = unknown ? UNKNOWN_ANSWER : userText;
    data[qId] = storedText;
    data[field] = storedText;
    // Clearing stale enum values is essential when replacing an option with free text.
    delete data[`${qId}Value`];
    delete data[`${field}Value`];
    if (optionValue && !unknown) {
      data[`${qId}Value`] = optionValue;
      data[`${field}Value`] = optionValue;
    }
    this.reviewRequired[phase] = (this.reviewRequired[phase] || []).filter(id => id !== qId);
    this.completedPhases[phase] = false;
    if (oldValue !== storedText || previous?.optionValue !== optionValue) this.invalidateDependentPhases(phase);

    for (const entry of this.unknowns.filter(u => u.phase === phase && u.questionId === qId && u.status !== UNKNOWN_STATUS.RESOLVED)) {
      UnknownsManager.resolveUnknown(this.unknowns, entry.id, `پاسخ جایگزین ثبت شد: ${record.id}`);
    }
    if (unknown) {
      const entry = UnknownsManager.createUnknown({
        phase, questionId: qId, category: unknownIntent.category || 'EXPLICIT_IGNORANCE',
        reason: `${record.label}: ${userText}`,
        actionItem: unknownIntent.actionItem || `داده واقعی «${record.label}» را جمع‌آوری و این پاسخ را ویرایش کنید.`,
        source: record.source, existingCount: this.unknowns.length,
      });
      entry.answerId = record.id;
      this.unknowns.push(entry);
    }
    if (phase === 1) {
      if (qId === 'step0_description') {
        for (const key of Object.keys(data.inferredFields || {})) delete data[key];
        data.inferredFields = {};
        if (oldValue && oldValue !== storedText) this.reviewRequired[1] = INTERVIEW_FIELDS.filter(item => item.phase === 1 && item.questionId !== qId && data[item.field]).map(item => item.questionId);
        delete data.taxonomyId;
        delete data.resolvedBT;
        if (typeof optionValue === 'string' && /^BT-\d+$/i.test(optionValue)) data.taxonomyId = optionValue.toUpperCase();
      }
      if (!unknown && ['step0_description', 'step0_diagnostic_probing'].includes(qId)) {
        const slots = parseSemanticInput(userText, this.businessContext).extractedSlots;
        const inferred = { customerModel: slots?.customerModel, channelModel: slots?.channels,
          scale: slots?.scale, geographyFromFreeform: slots?.geography, primaryBottleneck: slots?.primaryBottleneck };
        for (const [key, value] of Object.entries(inferred)) {
          if (value && (!data[key] || data.inferredFields?.[key] === qId)) {
            data[key] = value;
            (data.inferredFields ||= {})[key] = qId;
          }
        }
        if (!optionValue && slots?.businessTypeMatch && qId === 'step0_description') {
          data.descriptionValue = slots.businessTypeMatch.id;
          data.taxonomyId = slots.businessTypeMatch.id;
        }
      }
      this.businessContext = classifyBusinessContext(this.phaseData);
    }
    const ledger = activeAnswers(this.answerRecords).map(a => ({
      id: `${a.kind}-${a.id}`, answerId: a.id, phase: a.phase, questionId: a.questionId,
      statement: `${a.label || FIELD_BY_QUESTION[a.questionId]?.label || a.questionId}: ${a.text}`,
      source: a.source, kind: a.kind,
    }));
    this.facts = ledger.filter(a => a.kind === 'FACT');
    this.decisions = ledger.filter(a => a.kind === 'DECISION');
    this.assumptions = ledger.filter(a => ['ASSUMPTION', 'UNKNOWN'].includes(a.kind));
    this.refreshContradictions();
    this.currentStepIndex++;
    this.reviewCursor = reviewing && this.currentStepIndex < this.getCurrentPhaseQuestions().length ? this.currentStepIndex : null;
    const nextQuestion = this.getCurrentQuestion();
    if (!nextQuestion) return this.finalizeCurrentPhase();
    return { reply: unknown ? 'پاسخ به عنوان مجهول رسمی ثبت شد.' : 'پاسخ ثبت شد.', nextQuestion, isCompleted: false, answerId: record.id };
  }

  refreshContradictions() {
    const detected = ContradictionEngine.detectContradictions(this);
    const key = c => c.ruleId || `${c.statementA}::${c.statementB}`;
    const detectedKeys = new Set(detected.map(key));
    for (const old of this.contradictions) {
      if (old.source === 'RULE' && !detectedKeys.has(key(old)) && old.resolutionStatus === CONTRADICTION_STATUS.UNRESOLVED) {
        old.resolutionStatus = CONTRADICTION_STATUS.RESOLVED;
        old.resolution = 'داده مبنا اصلاح شد؛ شرط تعارض دیگر برقرار نیست.';
        old.resolvedAt = new Date().toISOString();
      }
    }
    for (const item of detected) {
      const existing = this.contradictions.find(c => key(c) === key(item) && c.resolutionStatus === CONTRADICTION_STATUS.UNRESOLVED);
      if (!existing) this.contradictions.push({ ...item, source: 'RULE' });
    }
  }

  getPhaseName(p) {
    const phaseNames = {
      1: "کشف و بنیاد کسب‌وکار",
      2: "هوش بازار و پژوهش مشتری",
      3: "استراتژی و جهت‌گیری برند",
      4: "هویت و شخصیت برند",
      5: "سیستم هویت کلامی و پیام‌رسانی",
      6: "نام‌گذاری، شعار و جهت‌گیری خلاقانه",
      7: "سیستم طراحی هویت بصری",
      8: "برنامه فعال‌سازی اجرایی، PR و مدیریت اعتبار"
    };
    return phaseNames[p] || `فاز ${p}`;
  }

  finalizeCurrentPhase() {
    const p = this.currentPhase;

    if (p === 1) {
      this.businessContext = classifyBusinessContext(this.phaseData);
    }

    // Real Phase Gate Validation (Requirement R2)
    const gateResult = validatePhaseGate(p, this);
    this.lastGateResult = gateResult;

    if (!gateResult.passed) {
      this.completedPhases[p] = false;
      const reasonsList = gateResult.blockingReasons.map(r => `- ❌ ${r}`).join("\n");
      const missingList = gateResult.missingFacts.length > 0
        ? `\n\n📌 **اقلام اطلاعاتی مفقود:**\n` + gateResult.missingFacts.map(f => `- ⚠️ ${f}`).join("\n")
        : "";

      return {
        reply: `🛑 **توقف در گیت خروج فاز ${p} (${this.getPhaseName(p)})**\n\nامکان نهایی‌سازی فاز جاری وجود ندارد زیرا الزامات ورود به مرحله بعد محقق نشده است:\n\n${reasonsList}${missingList}\n\n💡 *لطفاً موارد فوق را شفاف‌سازی کنید تا امکان عبور از گیت و صدور سند فراهم شود.*`,
        nextQuestion: null,
        isCompleted: false,
        gatePassed: false,
        gateResult: gateResult,
        completedPhase: null,
        nextPhase: null,
        isFinalGrandFinale: false
      };
    }

    this.completedPhases[p] = true;
    if (this.phaseStatus[p] === "INVALIDATED") {
      delete this.phaseStatus[p];
    }

    const phaseNames = {
      1: "کشف و بنیاد کسب‌وکار",
      2: "هوش بازار و پژوهش مشتری",
      3: "استراتژی و جهت‌گیری برند",
      4: "هویت و شخصیت برند",
      5: "سیستم هویت کلامی و پیام‌رسانی",
      6: "نام‌گذاری، شعار و جهت‌گیری خلاقانه",
      7: "سیستم طراحی هویت بصری",
      8: "برنامه فعال‌سازی اجرایی، PR و مدیریت اعتبار"
    };

    if (p < 8) {
      return {
        reply: `🎉 **تبریک می‌گویم! تمامی مراحل فاز ${p} (${phaseNames[p]}) با موفقیت تکمیل شد.**\n\nگیت اعتبارسنجی با نمره شواهد ${gateResult.evidenceScore}/100 تایید شد و سند تخصصی صادر گردید.\n\n👇 **روی دکمه «ورود به فاز ${p + 1}: ${phaseNames[p + 1]}» کلیک کنید تا ادامه دهیم:**`,
        nextQuestion: null,
        isCompleted: true,
        gatePassed: true,
        gateResult: gateResult,
        completedPhase: p,
        nextPhase: p + 1,
        isFinalGrandFinale: false
      };
    } else {
      return {
        reply: `🏆 **شاهکار است! تبریک صمیمانه، شما تمامی ۸ فاز برندینگ و فعال‌سازی اجرایی را با موفقیت ۱۰۰٪ نهایی کردید!**\n\nاکنون کل هویت برند، تمایز محوری، کاراکتر، پیام‌رسانی، نام، سیستم بصری و ماشین فعال‌سازی تجاری و سئوی شما به صورت علمی و هماهنگ تدوین شد.\n\n🌟 **«کتابچه جامع استراتژی و ماشین اجرای برند (Master Brand Book & Execution Machine)»** شامل تمامی اسناد ۸ گانه تولید شده و آماده دانلود یکپارچه است!`,
        nextQuestion: null,
        isCompleted: true,
        gatePassed: true,
        gateResult: gateResult,
        completedPhase: 8,
        nextPhase: null,
        isFinalGrandFinale: true
      };
    }
  }

  generateDeliverableData(phaseNum = this.currentPhase) {
    return generateDeliverable(phaseNum, this.phaseData, this.businessContext, this.decisions, this.facts, this.unknowns, {
      answerRecords: this.answerRecords, completedPhases: this.completedPhases,
      contradictions: this.contradictions, phaseStatus: this.phaseStatus, revision: this.revision,
    });
  }

  generateMarkdownText(phaseNum = this.currentPhase) {
    return deliverableToMarkdown(this.generateDeliverableData(phaseNum));
  }
}
