export const REASONING_SCHEMA_VERSION = '3.0.0';
export const REASONING_ENGINE_VERSION = '3.0.0-foundation';

export const NODE_TYPES = Object.freeze({
  EVIDENCE: 'EVIDENCE',
  CONTEXT_AXIS_VALUE: 'CONTEXT_AXIS_VALUE',
  DECISION_NODE: 'DECISION_NODE',
  CALCULATION: 'CALCULATION',
  EXTERNAL_KNOWLEDGE_CLAIM: 'EXTERNAL_KNOWLEDGE_CLAIM',
  PROPOSAL: 'PROPOSAL',
  DECISION: 'DECISION',
  RISK: 'RISK',
  CONTRADICTION: 'CONTRADICTION',
  OUTPUT_CLAIM: 'OUTPUT_CLAIM',
  OUTPUT_SECTION: 'OUTPUT_SECTION',
  GATE: 'GATE',
});

export const EDGE_TYPES = Object.freeze({
  REQUIRES: 'REQUIRES',
  INFLUENCES: 'INFLUENCES',
  DERIVES: 'DERIVES',
  ACTIVATES: 'ACTIVATES',
  INVALIDATES: 'INVALIDATES',
  CONTRADICTS: 'CONTRADICTS',
  SUPPORTS: 'SUPPORTS',
  BLOCKS: 'BLOCKS',
  SUPERSEDES: 'SUPERSEDES',
});

export const ENTITY_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  CONFIRMED: 'CONFIRMED',
  PROVISIONAL: 'PROVISIONAL',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  BLOCKED: 'BLOCKED',
  STALE: 'STALE',
  SUPERSEDED: 'SUPERSEDED',
  DEPRECATED: 'DEPRECATED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

const T = ENTITY_STATUS;

export const ALLOWED_STATUS_TRANSITIONS = Object.freeze({
  [T.DRAFT]: Object.freeze([T.ACTIVE, T.PROVISIONAL, T.BLOCKED, T.DEPRECATED]),
  [T.ACTIVE]: Object.freeze([T.CONFIRMED, T.PROVISIONAL, T.NEEDS_REVIEW, T.BLOCKED, T.STALE, T.SUPERSEDED, T.DEPRECATED, T.NOT_APPLICABLE]),
  [T.CONFIRMED]: Object.freeze([T.NEEDS_REVIEW, T.STALE, T.SUPERSEDED, T.DEPRECATED]),
  [T.PROVISIONAL]: Object.freeze([T.CONFIRMED, T.NEEDS_REVIEW, T.BLOCKED, T.STALE, T.SUPERSEDED, T.DEPRECATED]),
  [T.NEEDS_REVIEW]: Object.freeze([T.ACTIVE, T.CONFIRMED, T.PROVISIONAL, T.BLOCKED, T.STALE, T.SUPERSEDED, T.DEPRECATED]),
  [T.BLOCKED]: Object.freeze([T.ACTIVE, T.NEEDS_REVIEW, T.PROVISIONAL, T.SUPERSEDED, T.DEPRECATED]),
  [T.STALE]: Object.freeze([T.ACTIVE, T.NEEDS_REVIEW, T.SUPERSEDED, T.DEPRECATED]),
  [T.SUPERSEDED]: Object.freeze([T.DEPRECATED]),
  [T.DEPRECATED]: Object.freeze([]),
  [T.NOT_APPLICABLE]: Object.freeze([T.ACTIVE, T.DEPRECATED]),
});

export const isNodeType = value => Object.values(NODE_TYPES).includes(value);
export const isEdgeType = value => Object.values(EDGE_TYPES).includes(value);
export const isEntityStatus = value => Object.values(ENTITY_STATUS).includes(value);

export function canTransitionStatus(from, to) {
  if (from === to) return true;
  return Boolean(ALLOWED_STATUS_TRANSITIONS[from]?.includes(to));
}
